travis:
  secure:
    BINSTAR_TOKEN: NFUNu6C8DhCdwKgTqVaKYRDpWdROtj8newN60ROWcif8e9HV5FH1qEQGj5GO+H+fpvvQiglItVDV0c4Aonn7FsOOlbmjITFR6hCrG/GfK+DHtZaLUt826/JR+Bj0onWe4939zllu++VOdgo2nxZBMWphupHgemEtNexYQqSH3RMoAdBHAIaSCULjmyYjxHEFyESDOJ3AoK0YT5m3pZQAQ8gwd1eGQhEM/K96EzgBiHryyCR0H5Ymoliswm5u3Gn902LcU0/yH3E6DilFiwD5po9L91X34pndQh7fPq7Hh7S65NFjI+7kMtL5Aa04+ffibaCO5UiAJKNMSKhF+laAlQrmMgRvEWx50kshFH2cWvw3tu2k5P3HWbzfVAktdSoVxDiKgRsqZ+SntJtzHdZE/x76MYRcgp+evLQpOa0j/jDs/NUbFczafICOd6XyBgx1FEWysrsJRwjtoaZ3s9sbDB9/ZQdPjz0D+++p6z3odoCHP3hSOAom7HZcn71F2dG+iZc4iVbR3PCwLlzDX2iDJu3JROkWoGEB3i1E6i5J6Bx23tWrYl6MoGGjiI1l3ZQ1DXBwCVd2p9QZVTJttHz88uThT6ipd7Wnb3hJGWc8fUlnVpabsbiCJsEuXNTuttka7P/TkGeZNAIof7DlliOZpQpeEsaz4AtxPZIK2i7KjSU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
