travis:
  secure:
    BINSTAR_TOKEN: KfcQ+y3WeDJ1KFqLb0RJFISmu0ajj3hTtvMcz9D8i4vgfcLrIwO81tx68073rNKRu5tBnrLsGfoCG4mQrdRdK0nA84aZRDHTTv5xMHUofE90wN5EeFA6lCL8/tmgdYx8yJ6VGtnFhT1KM745OAfQ9cdoNzIYaQhyTTnwfTIuAkApJ7bygzYjVoAZZY7oqE//BoMmjnbdXw5yXTPKr/MBRvkHKuwfTvWT8mJdzWvhbQhslQ3nIgNH9jc39KrQVzQ4G06kSM/XsJKyl+wYcnT19Wt3f0xgqidYR0Fx/BQxEkvHDtRGQTuzMlrDw9BN2X6OzEgs1GGHYKsvemDRNyb+rP5KRTH0kz91e7qklKWr5OLJtfXqdQ6ig9YP+E8kTf8bd7ybrK+Jgs0FuEvMm7ZEqo8iAuiDU9XiLMIKBNwx9rlaxtQADXmMg2OhQ8O9YKrTimHX3tvzx7TuiX7Y8+Wf9K/x54Vfyf55Nxe7B9hVRSBcK1Xy/g2AtBlYighFzMxo/zwCW8uRmvBHLkTwqYFtRX1VKJIHf1q85zbJcSwc2LBKhQjYpE8SAOZqwAcjT2evxwvacGRv52Y1L/25ISjNcIjoeaS7gOgp9YNPa6rMGz0ejr4nwadlgzdnLTmPP/aGK4uoneRBUD++EMEME/eC84sYNmgrhs8cgrylOYqrCYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
